{
 "title": "My dashboard with azure",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Avg CPU Credits Consumed for ubuntu-grafana",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Percentage CPU",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "resourceGroup": "test-server-ubuntu_group",
      "resourceName": "ubuntu-grafana",
      "timeGrain": "PT1M",
      "top": ""
     },
     "subscription": "9a882a7a-673f-46ce-811f-beed0743423f"
    }
   ]
  },
  {
   "title": "Avalable Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Available Memory Bytes",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "resourceGroup": "test-server-ubuntu_group",
      "resourceName": "ubuntu-grafana",
      "timeGrain": "auto"
     },
     "subscription": "9a882a7a-673f-46ce-811f-beed0743423f"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Total network",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Network In Total",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "resourceGroup": "test-server-ubuntu_group",
      "resourceName": "ubuntu-grafana",
      "timeGrain": "auto"
     },
     "subscription": "9a882a7a-673f-46ce-811f-beed0743423f"
    }
   ]
  }
 ]
}